apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-lab 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kwandao6509650245/vote-lab.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: vote-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
