apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"vote-front"},"name":"vote-front","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"vote-front"}},"template":{"metadata":{"labels":{"app":"vote-front"}},"spec":{"containers":[{"env":[{"name":"REDIS","value":"vote-back"}],"image":"bitchecker007/vote-front:1.0","imagePullPolicy":"Always","name":"vote-front","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2025-08-13T09:33:24Z"
  generation: 2
  labels:
    app: vote-front
  name: vote-front
  namespace: vote-app
  resourceVersion: "745275"
  uid: 19dff4b0-c9ad-480f-965a-d708aadcc0cb
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vote-front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vote-front
    spec:
      containers:
      - env:
        - name: REDIS
          value: vote-back
        image: bitchecker007/vote-front:1.0
        imagePullPolicy: Always
        name: vote-front
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-08-13T09:33:24Z"
    lastUpdateTime: "2025-08-13T10:03:06Z"
    message: ReplicaSet "vote-front-68d9c5cd8b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-08-15T08:36:16Z"
    lastUpdateTime: "2025-08-15T08:36:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
