apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-votelab
  namespace: vote-app
  labels:
    pvname: pv-votelab
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/pv-votelab
