apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-votelab
  namespace: vote-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      pvname: pv-votelab
  volumeMode: Filesystem
